# Generated by Django 5.0.3 on 2024-03-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="последнее обновление"
            ),
        ),
    ]
